In [2]:
from pysentimiento import create_analyzer
import pandas as pd

In [8]:
model_analyser_sent = create_analyzer(task="sentiment", lang="pt")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [3]:
df = pd.read_csv("dados/frases.csv")

In [4]:
df.head()

   ID                                              Frase
0   1  Estou super feliz com o resultado da minha apr...
1   2  Fiquei decepcionado porque o voo foi cancelado...
2   3  A reunião com o cliente está marcada para as 1...
3   4  Adorei o restaurante novo; a comida estava del...
4   5  Estou cansado de esperar uma resposta que nunc...

In [5]:
df.tail()

    ID                                              Frase
22  23  Que dia maravilhoso para passear no parque com...
23  24  A entrega atrasou de novo e ninguém me deu uma...
24  25  O professor explicou o conteúdo da prova na úl...
25  26  Agradeço de coração por todo o carinho e a aju...
26  27  Fiquei chateado com a forma como fui tratado n...

In [6]:
df["Frase"]

0     Estou super feliz com o resultado da minha apr...
1     Fiquei decepcionado porque o voo foi cancelado...
2     A reunião com o cliente está marcada para as 1...
3     Adorei o restaurante novo; a comida estava del...
4     Estou cansado de esperar uma resposta que nunc...
5     O documento foi salvo na pasta compartilhada d...
6     Que orgulho ver meu irmão se formando depois d...
7     Não gostei do filme; a história era confusa e ...
8     O ônibus passa a cada vinte minutos neste horá...
9     Recebi uma notícia maravilhosa e mal consigo c...
10    Estou irritado com o barulho dos vizinhos que ...
11    A atualização do sistema será feita durante o ...
12    Foi uma experiência incrível viajar com meus a...
13          Me sinto sozinho desde que mudei de cidade.
14    O treino de hoje começou às sete e terminou às...
15    Estou ansioso para o resultado da entrevista d...
16    O atendimento do suporte foi péssimo e ninguém...
17    Parabéns pela promoção, você merece muito essa...
18    A loja fecha às dezoito horas de segunda a sexta.
19    Estou muito satisfeito com a qualidade do prod...
20    Perdi meu celular no metrô e agora estou deses...
21    Choveu bastante durante a tarde, mas o tempo m...
22    Que dia maravilhoso para passear no parque com...
23    A entrega atrasou de novo e ninguém me deu uma...
24    O professor explicou o conteúdo da prova na úl...
25    Agradeço de coração por todo o carinho e a aju...
26    Fiquei chateado com a forma como fui tratado n...
Name: Frase, dtype: object

In [9]:
prev_result = model_analyser_sent.predict(df["Frase"])

Map:   0%|          | 0/27 [00:00<?, ? examples/s]

/home/germano/Documentos/Automação Completa com Python/venv/lib/python3.10/site-packages/torch/utils/data/dataloader.py:759: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

In [10]:
prev_result

[AnalyzerOutput(output=POS, probas={POS: 0.979, NEU: 0.018, NEG: 0.003}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.991, NEU: 0.006, POS: 0.003}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.954, POS: 0.031, NEG: 0.014}),
 AnalyzerOutput(output=POS, probas={POS: 0.993, NEU: 0.005, NEG: 0.002}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.896, NEU: 0.086, POS: 0.018}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.902, POS: 0.075, NEG: 0.023}),
 AnalyzerOutput(output=POS, probas={POS: 0.949, NEU: 0.041, NEG: 0.010}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.992, NEU: 0.006, POS: 0.003}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.882, NEG: 0.084, POS: 0.034}),
 AnalyzerOutput(output=POS, probas={POS: 0.977, NEU: 0.019, NEG: 0.004}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.984, NEU: 0.010, POS: 0.006}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.961, POS: 0.021, NEG: 0.018}),
 AnalyzerOutput(output=POS, probas={POS: 0.980, NEU: 0.017, NEG: 0.002}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.763, NEU: 0.228, POS: 0.009}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.963, POS: 0.021, NEG: 0.016}),
 AnalyzerOutput(output=POS, probas={POS: 0.871, NEU: 0.121, NEG: 0.008}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.985, NEU: 0.011, POS: 0.004}),
 AnalyzerOutput(output=POS, probas={POS: 0.976, NEU: 0.020, NEG: 0.004}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.958, POS: 0.024, NEG: 0.017}),
 AnalyzerOutput(output=POS, probas={POS: 0.973, NEU: 0.025, NEG: 0.003}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.900, NEU: 0.090, POS: 0.011}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.837, POS: 0.131, NEG: 0.032}),
 AnalyzerOutput(output=POS, probas={POS: 0.982, NEU: 0.014, NEG: 0.003}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.903, NEU: 0.091, POS: 0.005}),
 AnalyzerOutput(output=NEU, probas={NEU: 0.925, NEG: 0.044, POS: 0.031}),
 AnalyzerOutput(output=POS, probas={POS: 0.974, NEU: 0.023, NEG: 0.003}),
 AnalyzerOutput(output=NEG, probas={NEG: 0.978, NEU: 0.019, POS: 0.003})]

In [12]:
sentiment = []
for result in prev_result:
    sentiment.append(result.output)

In [13]:
df["sentimento"] = sentiment

In [14]:
df

    ID                                              Frase sentimento
0    1  Estou super feliz com o resultado da minha apr...        POS
1    2  Fiquei decepcionado porque o voo foi cancelado...        NEG
2    3  A reunião com o cliente está marcada para as 1...        NEU
3    4  Adorei o restaurante novo; a comida estava del...        POS
4    5  Estou cansado de esperar uma resposta que nunc...        NEG
5    6  O documento foi salvo na pasta compartilhada d...        NEU
6    7  Que orgulho ver meu irmão se formando depois d...        POS
7    8  Não gostei do filme; a história era confusa e ...        NEG
8    9  O ônibus passa a cada vinte minutos neste horá...        NEU
9   10  Recebi uma notícia maravilhosa e mal consigo c...        POS
10  11  Estou irritado com o barulho dos vizinhos que ...        NEG
11  12  A atualização do sistema será feita durante o ...        NEU
12  13  Foi uma experiência incrível viajar com meus a...        POS
13  14        Me sinto sozinho desde que mudei de cidade.        NEG
14  15  O treino de hoje começou às sete e terminou às...        NEU
15  16  Estou ansioso para o resultado da entrevista d...        POS
16  17  O atendimento do suporte foi péssimo e ninguém...        NEG
17  18  Parabéns pela promoção, você merece muito essa...        POS
18  19  A loja fecha às dezoito horas de segunda a sexta.        NEU
19  20  Estou muito satisfeito com a qualidade do prod...        POS
20  21  Perdi meu celular no metrô e agora estou deses...        NEG
21  22  Choveu bastante durante a tarde, mas o tempo m...        NEU
22  23  Que dia maravilhoso para passear no parque com...        POS
23  24  A entrega atrasou de novo e ninguém me deu uma...        NEG
24  25  O professor explicou o conteúdo da prova na úl...        NEU
25  26  Agradeço de coração por todo o carinho e a aju...        POS
26  27  Fiquei chateado com a forma como fui tratado n...        NEG